PUT http://localhost:8080/api/v1/books/7f51cb79-03e6-45ba-9b06-178d3affaa7b
content-type: application/json

{
    "title": "Python Crash Course",
    "author": "Eric Matthes",
    "isbn": "0596007124",
    "status": "read",
    "rating": 1.5,
    "notes": "Great for learning python. Pyhton is really fun."
}

# {
#     "status": "unread"
# }

# {
#     "rating": 4
# }
